console.log("👥 Usuarios Fase 4.1.2");
let sb=null, cache=[], channel=null;
const roles={admin:"Administrador",gerente_rh:"Gerente RH",reclutadora:"Reclutadora",ejecutivo:"Ejecutivo"};
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function client(){if(sb)return sb;if(window.initSupabase)sb=await window.initSupabase();else if(window.getSupabaseClient)sb=await window.getSupabaseClient();else sb=window.supabaseClient||window.supabaseDB;if(!sb)throw Error("Cliente Supabase no disponible");return sb}
function can(p){return !window.tienePermiso||window.tienePermiso(p)}
async function load(){const c=await client();const {data,error}=await c.from("profiles").select("id,email,nombre,role_code,activo,requiere_cambio_password").order("nombre");if(error)throw error;cache=data||[];render();console.log("✅ Usuarios cargados:",cache.length)}
function render(){let b=$("usuariosBody");if(!cache.length){b.innerHTML='<tr><td colspan="6" class="empty-state">No hay usuarios registrados</td></tr>';return}b.innerHTML=cache.map(u=>`<tr><td><strong>${esc(u.nombre||"Sin nombre")}</strong></td><td>${esc(u.email||"")}</td><td><span class="pill">${esc(roles[u.role_code]||u.role_code||"Sin rol")}</span></td><td><span class="pill ${u.activo!==false?"ok":"off"}">${u.activo!==false?"Activo":"Inactivo"}</span></td><td>${u.requiere_cambio_password?'<span class="pill warn">Pendiente</span>':'No'}</td><td class="acts">${can("editar_usuario")?`<button onclick="editUser('${u.id}')">✏️</button><button onclick="resetPass('${u.id}')">🔑</button>`:""}</td></tr>`).join("")}
function open(id){$(id).classList.add("show")}function closeAll(){document.querySelectorAll(".modal-u").forEach(x=>x.classList.remove("show"))}
window.editUser=id=>{let u=cache.find(x=>x.id===id);if(!u)return;$("modalTitulo").textContent="Editar usuario";$("usuarioId").value=u.id;$("usuarioNombre").value=u.nombre||"";$("usuarioEmail").value=u.email||"";$("usuarioEmail").readOnly=true;$("usuarioRol").value=u.role_code||"reclutadora";$("usuarioActivo").value=String(u.activo!==false);$("wrapTemp").style.display="none";$("wrapActivo").style.display="block";open("modalUsuario")}
window.resetPass=id=>{let u=cache.find(x=>x.id===id);$("passwordUserId").value=id;$("passwordUsuario").textContent=u?`${u.nombre} · ${u.email}`:"";$("passwordTemporal").value="";open("modalPassword")}
async function invoke(body){const c=await client();const {data,error}=await c.functions.invoke("admin-users",{body});if(error)throw error;if(!data?.ok)throw Error(data?.error||"Operación no completada");return data}
$("btnNuevo")?.addEventListener("click",()=>{if(!can("crear_usuario"))return alert("Sin permiso");$("formUsuario").reset();$("usuarioId").value="";$("modalTitulo").textContent="Nuevo usuario";$("usuarioEmail").readOnly=false;$("wrapTemp").style.display="block";$("wrapActivo").style.display="none";open("modalUsuario")});
$("formUsuario")?.addEventListener("submit",async e=>{e.preventDefault();try{let id=$("usuarioId").value;if(id){await invoke({action:"update",user_id:id,nombre:$("usuarioNombre").value.trim(),role_code:$("usuarioRol").value,activo:$("usuarioActivo").value==="true"})}else{let pw=$("usuarioPassword").value;if(pw.length<8)throw Error("La contraseña temporal debe tener al menos 8 caracteres");await invoke({action:"create",nombre:$("usuarioNombre").value.trim(),email:$("usuarioEmail").value.trim(),role_code:$("usuarioRol").value,password:pw})}closeAll();await load();alert("✅ Usuario guardado")}catch(err){console.error(err);alert("❌ "+err.message)}});
$("formPassword")?.addEventListener("submit",async e=>{e.preventDefault();try{let pw=$("passwordTemporal").value;if(pw.length<8)throw Error("Mínimo 8 caracteres");await invoke({action:"reset_password",user_id:$("passwordUserId").value,password:pw});closeAll();await load();alert("✅ Contraseña temporal asignada")}catch(err){console.error(err);alert("❌ "+err.message)}});
document.querySelectorAll("[data-close]").forEach(x=>x.addEventListener("click",closeAll));
document.addEventListener("DOMContentLoaded",async()=>{try{if(!can("ver_usuarios"))return;await load();const c=await client();channel=c.channel("profiles-users-412").on("postgres_changes",{event:"*",schema:"public",table:"profiles"},()=>load()).subscribe(s=>{if(s==="SUBSCRIBED")console.log("📡 Realtime Usuarios activo")});console.log("✅ Usuarios Fase 4.1.2 inicializado")}catch(e){console.error("❌ Usuarios:",e)}});
