-- Fase 4.4. Ejecutar como propietario en Supabase SQL Editor.
-- PRECAUCIÓN: realizar backup antes de migrar. No sustituye políticas RLS de datos de negocio.
BEGIN;
CREATE TABLE IF NOT EXISTS public.rbac_roles (codigo text PRIMARY KEY, nombre text NOT NULL, descripcion text NOT NULL DEFAULT '', activo boolean NOT NULL DEFAULT true, protegido boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.rbac_permisos (codigo text PRIMARY KEY, nombre text NOT NULL, modulo text NOT NULL);
CREATE TABLE IF NOT EXISTS public.rbac_rol_permisos (rol_codigo text NOT NULL REFERENCES public.rbac_roles(codigo) ON DELETE CASCADE, permiso_codigo text NOT NULL REFERENCES public.rbac_permisos(codigo) ON DELETE CASCADE, PRIMARY KEY(rol_codigo,permiso_codigo));
ALTER TABLE public.rbac_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rbac_permisos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rbac_rol_permisos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.rbac_roles,public.rbac_permisos,public.rbac_rol_permisos FROM PUBLIC,anon,authenticated;
-- Bloquear modificación directa: exclusivamente RPC SECURITY DEFINER autorizada.
INSERT INTO public.rbac_roles(codigo,nombre,protegido) VALUES ('admin','Administrador',true) ON CONFLICT (codigo) DO UPDATE SET nombre=EXCLUDED.nombre, protegido=EXCLUDED.protegido;
INSERT INTO public.rbac_roles(codigo,nombre,protegido) VALUES ('gerente_rh','Gerente RH',false) ON CONFLICT (codigo) DO UPDATE SET nombre=EXCLUDED.nombre, protegido=EXCLUDED.protegido;
INSERT INTO public.rbac_roles(codigo,nombre,protegido) VALUES ('reclutadora','Reclutadora',false) ON CONFLICT (codigo) DO UPDATE SET nombre=EXCLUDED.nombre, protegido=EXCLUDED.protegido;
INSERT INTO public.rbac_roles(codigo,nombre,protegido) VALUES ('ejecutivo','Ejecutivo',false) ON CONFLICT (codigo) DO UPDATE SET nombre=EXCLUDED.nombre, protegido=EXCLUDED.protegido;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('administrar_requisicion','Administrar requisicion','Requisiciones') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('crear_candidato','Crear candidato','Candidatos') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('crear_requisicion','Crear requisicion','Requisiciones') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('crear_usuario','Crear usuario','Usuarios') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('editar_candidato','Editar candidato','Candidatos') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('editar_requisicion','Editar requisicion','Requisiciones') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('editar_usuario','Editar usuario','Usuarios') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('eliminar_candidato','Eliminar candidato','Candidatos') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('eliminar_requisicion','Eliminar requisicion','Requisiciones') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('eliminar_usuario','Eliminar usuario','Usuarios') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('gestionar_roles','Gestionar roles','Roles y seguridad') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('ver_candidatos','Ver candidatos','Candidatos') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('ver_configuracion','Ver configuracion','Otros módulos') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('ver_dashboard','Ver dashboard','Paneles') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('ver_dashboard_ejecutivo','Ver dashboard ejecutivo','Paneles') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('ver_ia','Ver ia','Otros módulos') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('ver_notificaciones','Ver notificaciones','Otros módulos') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('ver_perfil','Ver perfil','Otros módulos') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('ver_reclutadora','Ver reclutadora','Otros módulos') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('ver_reportes','Ver reportes','Otros módulos') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('ver_requisiciones','Ver requisiciones','Requisiciones') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('ver_seguimiento','Ver seguimiento','Otros módulos') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('ver_usuarios','Ver usuarios','Usuarios') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_permisos(codigo,nombre,modulo) VALUES ('ver_vacantes','Ver vacantes','Otros módulos') ON CONFLICT (codigo) DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','ver_dashboard') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','crear_requisicion') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','ver_requisiciones') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','editar_requisicion') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','eliminar_requisicion') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','administrar_requisicion') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','ver_reclutadora') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','ver_vacantes') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','ver_candidatos') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','crear_candidato') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','editar_candidato') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','eliminar_candidato') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','ver_seguimiento') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','ver_reportes') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','ver_dashboard_ejecutivo') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','ver_usuarios') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','crear_usuario') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','editar_usuario') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','eliminar_usuario') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','ver_configuracion') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','ver_notificaciones') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','ver_ia') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','ver_perfil') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('admin','gestionar_roles') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','ver_dashboard') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','crear_requisicion') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','ver_requisiciones') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','editar_requisicion') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','administrar_requisicion') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','ver_reclutadora') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','ver_vacantes') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','ver_candidatos') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','crear_candidato') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','editar_candidato') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','ver_seguimiento') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','ver_reportes') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','ver_dashboard_ejecutivo') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','ver_notificaciones') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','ver_ia') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('gerente_rh','ver_perfil') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('reclutadora','ver_dashboard') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('reclutadora','crear_requisicion') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('reclutadora','ver_requisiciones') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('reclutadora','editar_requisicion') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('reclutadora','administrar_requisicion') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('reclutadora','ver_reclutadora') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('reclutadora','ver_vacantes') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('reclutadora','ver_candidatos') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('reclutadora','crear_candidato') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('reclutadora','editar_candidato') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('reclutadora','ver_seguimiento') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('reclutadora','ver_notificaciones') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('reclutadora','ver_ia') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('reclutadora','ver_perfil') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('ejecutivo','ver_dashboard') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('ejecutivo','ver_requisiciones') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('ejecutivo','ver_vacantes') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('ejecutivo','ver_candidatos') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('ejecutivo','ver_seguimiento') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('ejecutivo','ver_reportes') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('ejecutivo','ver_dashboard_ejecutivo') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('ejecutivo','ver_notificaciones') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('ejecutivo','ver_ia') ON CONFLICT DO NOTHING;
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) VALUES ('ejecutivo','ver_perfil') ON CONFLICT DO NOTHING;

-- Compatibilidad con códigos legados sin tocar perfiles existentes.
CREATE OR REPLACE FUNCTION public.rbac_normalizar_codigo(p text) RETURNS text LANGUAGE sql IMMUTABLE SET search_path='' AS $$ SELECT CASE lower(trim(p)) WHEN 'administrador' THEN 'admin' WHEN 'gerente' THEN 'gerente_rh' ELSE lower(trim(p)) END $$;
CREATE OR REPLACE FUNCTION public.rbac_es_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT EXISTS(SELECT 1 FROM public.profiles p WHERE (p.id=auth.uid() OR p.auth_id=auth.uid()) AND public.rbac_normalizar_codigo(p.role_code)='admin' AND p.activo IS DISTINCT FROM false) $$;
CREATE OR REPLACE FUNCTION public.rbac_mis_permisos() RETURNS TABLE(permiso text) LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT rp.permiso_codigo FROM public.profiles p JOIN public.rbac_roles r ON r.codigo=public.rbac_normalizar_codigo(p.role_code) JOIN public.rbac_rol_permisos rp ON rp.rol_codigo=r.codigo WHERE (p.id=auth.uid() OR p.auth_id=auth.uid()) AND p.activo IS DISTINCT FROM false AND r.activo=true;
$$;
CREATE OR REPLACE FUNCTION public.rbac_tiene_permiso(p_permiso text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT EXISTS(SELECT 1 FROM public.rbac_mis_permisos() m WHERE m.permiso=p_permiso) $$;
CREATE OR REPLACE FUNCTION public.rbac_listar_roles() RETURNS TABLE(codigo text,nombre text,descripcion text,activo boolean,protegido boolean,permisos text[]) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$ BEGIN
 IF NOT public.rbac_tiene_permiso('ver_usuarios') AND NOT public.rbac_tiene_permiso('gestionar_roles') THEN RAISE EXCEPTION 'Acceso denegado'; END IF;
 RETURN QUERY SELECT r.codigo,r.nombre,r.descripcion,r.activo,r.protegido,coalesce(array_agg(rp.permiso_codigo ORDER BY rp.permiso_codigo) FILTER(WHERE rp.permiso_codigo IS NOT NULL),ARRAY[]::text[]) FROM public.rbac_roles r LEFT JOIN public.rbac_rol_permisos rp ON rp.rol_codigo=r.codigo GROUP BY r.codigo,r.nombre,r.descripcion,r.activo,r.protegido ORDER BY r.nombre;
END $$;
CREATE OR REPLACE FUNCTION public.rbac_catalogo_permisos() RETURNS TABLE(codigo text,nombre text,modulo text) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$ BEGIN
 IF NOT public.rbac_tiene_permiso('gestionar_roles') THEN RAISE EXCEPTION 'Acceso denegado'; END IF;
 RETURN QUERY SELECT p.codigo,p.nombre,p.modulo FROM public.rbac_permisos p ORDER BY p.modulo,p.nombre;
END $$;
CREATE OR REPLACE FUNCTION public.rbac_guardar_rol(p_codigo text,p_nombre text,p_descripcion text,p_activo boolean,p_permisos text[]) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$ DECLARE v_codigo text:=lower(trim(p_codigo)); BEGIN
 IF NOT public.rbac_es_admin() OR NOT public.rbac_tiene_permiso('gestionar_roles') THEN RAISE EXCEPTION 'Solo Administrador puede gestionar roles'; END IF;
 IF v_codigo !~ '^[a-z][a-z0-9_]{2,49}$' OR length(trim(p_nombre))<3 THEN RAISE EXCEPTION 'Código o nombre inválido'; END IF;
 IF EXISTS(SELECT 1 FROM public.rbac_roles WHERE codigo=v_codigo AND protegido) THEN RAISE EXCEPTION 'Rol protegido: no se permite modificar'; END IF;
 IF p_permisos IS NULL OR EXISTS(SELECT 1 FROM unnest(p_permisos) x WHERE NOT EXISTS(SELECT 1 FROM public.rbac_permisos y WHERE y.codigo=x)) THEN RAISE EXCEPTION 'Permisos inválidos'; END IF;
 INSERT INTO public.rbac_roles(codigo,nombre,descripcion,activo) VALUES(v_codigo,trim(p_nombre),coalesce(p_descripcion,''),p_activo) ON CONFLICT(codigo) DO UPDATE SET nombre=excluded.nombre,descripcion=excluded.descripcion,activo=excluded.activo;
 DELETE FROM public.rbac_rol_permisos WHERE rol_codigo=v_codigo;
 INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) SELECT v_codigo,unnest(p_permisos) ON CONFLICT DO NOTHING;
END $$;
-- El Administrador protegido conserva todos los permisos registrados, incluidos los nuevos.
INSERT INTO public.rbac_rol_permisos(rol_codigo,permiso_codigo) SELECT 'admin',codigo FROM public.rbac_permisos ON CONFLICT DO NOTHING;
REVOKE ALL ON FUNCTION public.rbac_es_admin(),public.rbac_normalizar_codigo(text),public.rbac_mis_permisos(),public.rbac_tiene_permiso(text),public.rbac_listar_roles(),public.rbac_catalogo_permisos(),public.rbac_guardar_rol(text,text,text,boolean,text[]) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.rbac_mis_permisos(),public.rbac_tiene_permiso(text),public.rbac_listar_roles(),public.rbac_catalogo_permisos(),public.rbac_guardar_rol(text,text,text,boolean,text[]) TO authenticated;
COMMIT;
